"""Configure the project-local MinerU runtime without changing other app settings.

The installer first runs --models-only, downloads and verifies the models, then
runs --configure-app. The final step also verifies models before writing settings.
"""
from __future__ import annotations

import argparse
import copy
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from uuid import uuid4


# Also usable in a portable app folder which does not contain the Python sources.
_FALLBACK_DEFAULTS = {
    "course_url": "https://www.bb.ustc.edu.cn/webapps/blackboard/execute/modulepage/view?course_id=_12345_1",
    "username": "",
    "bb": {"base_url": "https://www.bb.ustc.edu.cn", "course_id": "_12345_1", "timeout": 60},
    "ocr": {
        "mode": "command",
        "command": [],
        "endpoint": "http://127.0.0.1:8000/file_parse",
        "timeout": 1800,
        "backend": "pipeline",
        "extra_params": {},
    },
    "grading": {
        "base_url": "https://api.deepseek.com", "model": "deepseek-flash", "wire_api": "chat", "temperature": 0,
        "max_tokens": 16384, "timeout": 180, "max_input_chars": 100000, "extra_body": {},
    },
    "rubric": {"max_score": 10, "instructions": "", "reference_answer": ""},
}


class ConfigurationError(Exception):
    """A diagnostic that never contains configuration values or credentials."""


def _app_defaults(project: Path) -> dict:
    source = project / "src" / "bb_assistant" / "settings.py"
    if source.is_file():
        spec = importlib.util.spec_from_file_location("_bb_mineru_setup_settings", source)
        if spec is not None and spec.loader is not None:
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return copy.deepcopy(module.DEFAULTS)
    return copy.deepcopy(_FALLBACK_DEFAULTS)


def atomic_replace_with_backup(path: Path, content: bytes) -> bool:
    """Write by atomic replacement; keep a byte-for-byte backup when replacing."""
    path = Path(path)
    previous = path.read_bytes() if path.exists() else None
    if previous == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    if previous is not None:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        backup = path.with_name(f"{path.name}.before-mineru-{stamp}-{uuid4().hex[:8]}.bak")
        with backup.open("xb") as stream:
            stream.write(previous)
            stream.flush()
            os.fsync(stream.fileno())
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return True


def configure_models(project: Path) -> Path:
    project = Path(project).resolve()
    model_root = project / ".mineru" / "models"
    model_root.mkdir(parents=True, exist_ok=True)
    config = project / ".mineru" / "config.yaml"
    content = (
        "# Generated by BB Mark Assistant local MinerU setup.\n"
        "model:\n"
        "  source: local\n"
        f"  base_dir: {json.dumps(model_root.as_posix(), ensure_ascii=False)}\n"
        "  small_backend: onnx\n"
        "  vlm:\n"
        "    engine: llama-cpp\n"
        "    server_url: ''\n"
        "llm_aided:\n"
        "  features:\n"
        "    title_leveling: false\n"
        "    cross_page_table_cell_merge: false\n"
    )
    atomic_replace_with_backup(config, content.encode("utf-8"))
    return config


def mineru_command(project: Path) -> list[str]:
    project = Path(project).resolve()
    return [
        str(project / ".mineru-venv" / "Scripts" / "python.exe"),
        str(project / "scripts" / "mineru_local.py"),
        "parse", "{input}", "-o", "{output}/document.md",
        "--tier", "advanced", "--pages", "all", "--ocr-mode", "auto",
    ]


def application_targets(project: Path, app_data: list[Path] | None = None) -> list[Path]:
    if app_data is None:
        local = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "BBMarkAssistant"
        app_data = [Path(project) / "data", local]
    # A custom --app-data replaces both defaults and never touches live settings.
    result: list[Path] = []
    for path in app_data:
        target = Path(path).expanduser().resolve()
        if target not in result:
            result.append(target)
    return result


def configure_application(project: Path, app_data: list[Path] | None = None) -> list[Path]:
    project = Path(project).resolve()
    command = mineru_command(project)
    if not all(Path(path).is_file() for path in command[:2]):
        raise ConfigurationError("MinerU runtime or local wrapper is missing; run setup_mineru.ps1 first.")
    changes: list[tuple[Path, bytes]] = []
    for target in application_targets(project, app_data):
        path = target / "settings.json"
        if path.exists():
            try:
                config = json.loads(path.read_text(encoding="utf-8-sig"))
            except (ValueError, UnicodeError):
                raise ConfigurationError("Existing app settings are invalid; settings were left unchanged.") from None
            if not isinstance(config, dict) or not isinstance(config.get("ocr", {}), dict):
                raise ConfigurationError("Existing app settings have an invalid structure; settings were left unchanged.")
        else:
            config = _app_defaults(project)
        ocr = config.setdefault("ocr", {})
        ocr["mode"] = "command"
        ocr["command"] = command
        timeout = ocr.get("timeout", 1800)
        ocr["timeout"] = timeout if type(timeout) in (int, float) and timeout >= 1800 else 1800
        changes.append((path, (json.dumps(config, ensure_ascii=False, indent=2) + "\n").encode("utf-8")))
    # Parse and validate all targets before writing either one.
    for path, content in changes:
        atomic_replace_with_backup(path, content)
    return [path for path, _ in changes]


def verify_models(project: Path) -> None:
    # Advanced parsing shares Standard's models; the model CLI only accepts
    # basic/standard deployment tiers, not the advanced parsing tier.
    command = mineru_command(project)[:2]
    if not all(Path(path).is_file() for path in command):
        raise ConfigurationError("MinerU runtime or local wrapper is missing; run setup_mineru.ps1 first.")
    try:
        result = subprocess.run(
            command + ["models", "verify", "--tier", "standard", "--small-backend", "onnx", "--vlm-engine", "llama-cpp"],
            cwd=project, capture_output=True, timeout=180, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        raise ConfigurationError("MinerU model verification could not run; app settings were left unchanged.") from None
    if result.returncode:
        raise ConfigurationError("MinerU models are incomplete; finish setup_mineru.ps1 before configuring the app.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--models-only", action="store_true", help="Prepare local model configuration only, before downloading")
    mode.add_argument("--configure-app", action="store_true", help="Verify models and update app settings only")
    parser.add_argument("--app-data", action="append", type=Path, help="Only configure this app data directory; repeatable")
    args = parser.parse_args(argv)
    project = Path(__file__).resolve().parents[1]
    try:
        if not args.configure_app:
            configure_models(project)
            print("Project-local MinerU model configuration is ready.")
        if not args.models_only:
            verify_models(project)
            targets = configure_application(project, args.app_data)
            print(f"MinerU model verification passed; configured {len(targets)} app data location(s).")
            print("Restart BB Mark Assistant to reload its OCR settings.")
    except (ConfigurationError, OSError):
        # Do not echo arbitrary exception payloads from files, subprocesses or imports.
        print("MinerU configuration failed. Check the local runtime, downloaded models and settings file permissions. Existing settings backups are retained.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
